In [62]:
import numpy as np
import pandas as pd

In [63]:
df = pd.read_csv('/content/drive/MyDrive/Deep Learning/diabetes (1).csv')
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [64]:
df.corr()['Outcome']

Pregnancies                 0.221898
Glucose                     0.466581
BloodPressure               0.065068
SkinThickness               0.074752
Insulin                     0.130548
BMI                         0.292695
DiabetesPedigreeFunction    0.173844
Age                         0.238356
Outcome                     1.000000
Name: Outcome, dtype: float64

In [65]:
x = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [66]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
x = sc.fit_transform(x)

In [67]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [114]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense, Dropout

In [69]:
model = Sequential()

model.add(Dense(32, activation='relu', input_dim=8))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='Adam', loss='binary_crossentropy', metrics=['accuracy'])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [70]:
model.fit(x_train, y_train, batch_size=32, epochs=100, validation_data=(x_test, y_test))

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.4430 - loss: 0.7280 - val_accuracy: 0.6169 - val_loss: 0.6754
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6287 - loss: 0.6648 - val_accuracy: 0.7013 - val_loss: 0.6247
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6971 - loss: 0.6197 - val_accuracy: 0.7857 - val_loss: 0.5853
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7329 - loss: 0.5849 - val_accuracy: 0.7662 - val_loss: 0.5558
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7410 - loss: 0.5581 - val_accuracy: 0.7922 - val_loss: 0.5301
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7508 - loss: 0.5364 - val_accuracy: 0.7987 - val_loss: 0.5092
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7606 - loss: 0.5196 - val_accuracy: 0.7987 - val_loss: 0.4928
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7704 - loss: 0.5059 - val_accuracy: 0.7987 - val_loss: 0.4830
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7720 - loss: 0.4954 - val_accuracy: 0.7922 - val_loss: 0.4737
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7720 - loss: 0.4851 - val_accuracy: 0.7857 - val_loss: 0.4671
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7704 - loss: 0.4784 - val_accuracy: 0.7792 - val_loss: 0.4620
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7704 - loss: 0.4719 - val_accuracy: 0.7922 - val_loss: 0.4577
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7752 - loss: 0.4667 - val_accuracy: 0.7857 - val_loss: 0.4552
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7769 - loss: 0.4628 - val_accuracy: 0.7857 - val_loss: 0.4536
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7785 - loss: 0.4601 - val_accuracy: 0.7857 - val_loss: 0.4514
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7818 - loss: 0.4572 - val_accuracy: 0.7922 - val_loss: 0.4510
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7834 - loss: 0.4552 - val_accuracy: 0.7857 - val_loss: 0.4501
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7818 - loss: 0.4536 - val_accuracy: 0.7857 - val_loss: 0.4486
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7818 - loss: 0.4515 - val_accuracy: 0.7922 - val_loss: 0.4493
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7818 - loss: 0.4504 - val_accuracy: 0.7987 - val_loss: 0.4497
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7801 - loss: 0.4495 - val_accuracy: 0.7857 - val_loss: 0.4499
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7834 - loss: 0.4478 - val_accuracy: 0.7922 - val_loss: 0.4496
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7818 - loss: 0.4470 - val_accuracy: 0.7857 - val_loss: 0.4501
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7834 - loss: 0.4454 - val_accuracy: 0.7792 - val_loss: 0.4501
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7834 - loss: 0.4448 - val_accuracy: 0.7792 - val_loss: 0.4504
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7850 - loss: 0.4442 - val_accuracy: 0.7792 - val_loss: 0.4502
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7866 - loss: 0.4433 - val_accuracy: 0.7792 - val_loss: 0.4503
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7883 - loss: 0.4430 - val_accuracy: 0.7922 - val_loss: 0.4511
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7834 - loss: 0.4422 - val_accuracy: 0.7857 - val_loss: 0.4519
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7866 - loss: 0.4416 - val_accuracy: 0.7857 - val_loss: 0.4509
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4408 - val_accuracy: 0.7922 - val_loss: 0.4503
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4403 - val_accuracy: 0.7792 - val_loss: 0.4492
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4393 - val_accuracy: 0.7857 - val_loss: 0.4496
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4389 - val_accuracy: 0.7922 - val_loss: 0.4509
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4384 - val_accuracy: 0.7857 - val_loss: 0.4512
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4379 - val_accuracy: 0.7857 - val_loss: 0.4507
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4373 - val_accuracy: 0.7922 - val_loss: 0.4497
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4370 - val_accuracy: 0.8052 - val_loss: 0.4492
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4363 - val_accuracy: 0.8052 - val_loss: 0.4490
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4361 - val_accuracy: 0.8052 - val_loss: 0.4492
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4353 - val_accuracy: 0.8052 - val_loss: 0.4495
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4352 - val_accuracy: 0.8052 - val_loss: 0.4492
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4343 - val_accuracy: 0.8052 - val_loss: 0.4502
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4339 - val_accuracy: 0.8052 - val_loss: 0.4505
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4338 - val_accuracy: 0.8052 - val_loss: 0.4501
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4330 - val_accuracy: 0.8052 - val_loss: 0.4499
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4326 - val_accuracy: 0.7987 - val_loss: 0.4504
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4331 - val_accuracy: 0.8052 - val_loss: 0.4492
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4314 - val_accuracy: 0.8052 - val_loss: 0.4495
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4314 - val_accuracy: 0.8052 - val_loss: 0.4487
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7915 - loss: 0.4313 - val_accuracy: 0.8052 - val_loss: 0.4484
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4314 - val_accuracy: 0.8052 - val_loss: 0.4487
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4305 - val_accuracy: 0.8052 - val_loss: 0.4481
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4302 - val_accuracy: 0.7987 - val_loss: 0.4501
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4296 - val_accuracy: 0.7987 - val_loss: 0.4501
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4291 - val_accuracy: 0.7987 - val_loss: 0.4497
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4286 - val_accuracy: 0.7987 - val_loss: 0.4499
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4286 - val_accuracy: 0.7987 - val_loss: 0.4500
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7932 - loss: 0.4281 - val_accuracy: 0.7987 - val_loss: 0.4490
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4276 - val_accuracy: 0.7987 - val_loss: 0.4494
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4272 - val_accuracy: 0.7922 - val_loss: 0.4490
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4274 - val_accuracy: 0.7987 - val_loss: 0.4490
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7948 - loss: 0.4266 - val_accuracy: 0.7987 - val_loss: 0.4484
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4261 - val_accuracy: 0.7987 - val_loss: 0.4484
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4256 - val_accuracy: 0.7987 - val_loss: 0.4482
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4256 - val_accuracy: 0.7987 - val_loss: 0.4492
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4257 - val_accuracy: 0.7987 - val_loss: 0.4479
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4246 - val_accuracy: 0.7987 - val_loss: 0.4472
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4245 - val_accuracy: 0.7987 - val_loss: 0.4470
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4246 - val_accuracy: 0.7987 - val_loss: 0.4468
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4238 - val_accuracy: 0.7987 - val_loss: 0.4477
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4232 - val_accuracy: 0.7987 - val_loss: 0.4482
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4231 - val_accuracy: 0.7987 - val_loss: 0.4477
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4229 - val_accuracy: 0.8052 - val_loss: 0.4471
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4224 - val_accuracy: 0.8052 - val_loss: 0.4469
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4226 - val_accuracy: 0.7987 - val_loss: 0.4469
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4215 - val_accuracy: 0.7987 - val_loss: 0.4469
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4210 - val_accuracy: 0.7987 - val_loss: 0.4474
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4215 - val_accuracy: 0.7922 - val_loss: 0.4491
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4210 - val_accuracy: 0.8052 - val_loss: 0.4478
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4200 - val_accuracy: 0.8052 - val_loss: 0.4474
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4197 - val_accuracy: 0.7987 - val_loss: 0.4476
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4202 - val_accuracy: 0.7987 - val_loss: 0.4473
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4194 - val_accuracy: 0.7987 - val_loss: 0.4484
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4192 - val_accuracy: 0.7987 - val_loss: 0.4483
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4187 - val_accuracy: 0.7987 - val_loss: 0.4492
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4184 - val_accuracy: 0.8052 - val_loss: 0.4486
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4180 - val_accuracy: 0.7987 - val_loss: 0.4484
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4183 - val_accuracy: 0.7987 - val_loss: 0.4465
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4173 - val_accuracy: 0.8052 - val_loss: 0.4465
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4172 - val_accuracy: 0.7987 - val_loss: 0.4470
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4170 - val_accuracy: 0.7987 - val_loss: 0.4474
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4167 - val_accuracy: 0.8052 - val_loss: 0.4489
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4163 - val_accuracy: 0.7987 - val_loss: 0.4476
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4161 - val_accuracy: 0.8052 - val_loss: 0.4480
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4158 - val_accuracy: 0.7922 - val_loss: 0.4486
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8046 - loss: 0.4158 - val_accuracy: 0.7987 - val_loss: 0.4485
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4153 - val_accuracy: 0.8052 - val_loss: 0.4484
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7997 - loss: 0.4149 - val_accuracy: 0.8052 - val_loss: 0.4481
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4148 - val_accuracy: 0.7922 - val_loss: 0.4496

In [71]:
# 1. how to select appropriate optimizer
# 2. No. of nodes in a layer
# 3. How to select no. of layers
# 4. All in one model

In [72]:
import kerastuner as kt

In [73]:
def build_model(hp):

  model = Sequential()


  model.add(Dense(32, activation='relu', input_dim=8))
  model.add(Dense(1, activation='sigmoid'))

  optimizer = hp.Choice('optimizer', values = ['adam', 'rmsprop', 'adagrad', 'adadelta'])

  model.compile(optimizer=optimizer, loss='binary_crossentropy', metrics=['accuracy'])

  return model

In [74]:
tuner = kt.RandomSearch(build_model,
                        objective='val_accuracy',
                        max_trials=5)

Reloading Tuner from ./untitled_project/tuner0.json

In [75]:
tuner.search(x_train, y_train, epochs=5, validation_data=(x_test, y_test), verbose=1)

In [76]:
tuner.results_summary()

Results summary
Results in ./untitled_project
Showing 10 best trials
Objective(name="val_accuracy", direction="max")

Trial 3 summary
Hyperparameters:
optimizer: rmsprop
Score: 0.7597402334213257

Trial 1 summary
Hyperparameters:
optimizer: adam
Score: 0.7467532753944397

Trial 0 summary
Hyperparameters:
optimizer: adadelta
Score: 0.6428571343421936

Trial 2 summary
Hyperparameters:
optimizer: adagrad
Score: 0.5324675440788269

In [77]:
tuner.get_best_hyperparameters()[0].values

{'optimizer': 'rmsprop'}

In [78]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 6 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [79]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 32)             │           288 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 321 (1.25 KB)

 Trainable params: 321 (1.25 KB)

 Non-trainable params: 0 (0.00 B)

In [80]:
model.fit(x_train, y_train, batch_size=32, epochs=100, initial_epoch= 6,validation_data=(x_test, y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.7117 - loss: 0.5437 - val_accuracy: 0.7532 - val_loss: 0.5169
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7215 - loss: 0.5232 - val_accuracy: 0.7662 - val_loss: 0.5049
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7264 - loss: 0.5102 - val_accuracy: 0.7597 - val_loss: 0.4943
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7427 - loss: 0.4997 - val_accuracy: 0.7532 - val_loss: 0.4866
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7557 - loss: 0.4901 - val_accuracy: 0.7597 - val_loss: 0.4815
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7606 - loss: 0.4832 - val_accuracy: 0.7727 - val_loss: 0.4782
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7638 - loss: 0.4774 - val_accuracy: 0.7727 - val_loss: 0.4756
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7704 - loss: 0.4723 - val_accuracy: 0.7987 - val_loss: 0.4722
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7622 - loss: 0.4685 - val_accuracy: 0.7987 - val_loss: 0.4710
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7671 - loss: 0.4648 - val_accuracy: 0.7987 - val_loss: 0.4702
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7687 - loss: 0.4629 - val_accuracy: 0.7987 - val_loss: 0.4695
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7785 - loss: 0.4601 - val_accuracy: 0.7922 - val_loss: 0.4690
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7769 - loss: 0.4582 - val_accuracy: 0.7987 - val_loss: 0.4688
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4564 - val_accuracy: 0.7987 - val_loss: 0.4696
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4551 - val_accuracy: 0.7922 - val_loss: 0.4700
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4538 - val_accuracy: 0.8052 - val_loss: 0.4706
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4529 - val_accuracy: 0.7987 - val_loss: 0.4694
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4515 - val_accuracy: 0.7987 - val_loss: 0.4692
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4509 - val_accuracy: 0.8052 - val_loss: 0.4700
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4496 - val_accuracy: 0.8052 - val_loss: 0.4698
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4491 - val_accuracy: 0.7987 - val_loss: 0.4703
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4484 - val_accuracy: 0.7987 - val_loss: 0.4702
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4479 - val_accuracy: 0.7987 - val_loss: 0.4700
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4472 - val_accuracy: 0.7987 - val_loss: 0.4703
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4467 - val_accuracy: 0.7987 - val_loss: 0.4701
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4461 - val_accuracy: 0.8052 - val_loss: 0.4705
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4455 - val_accuracy: 0.7987 - val_loss: 0.4711
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4449 - val_accuracy: 0.7987 - val_loss: 0.4724
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7769 - loss: 0.4443 - val_accuracy: 0.7987 - val_loss: 0.4722
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4440 - val_accuracy: 0.7987 - val_loss: 0.4726
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4436 - val_accuracy: 0.7922 - val_loss: 0.4733
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4428 - val_accuracy: 0.7922 - val_loss: 0.4728
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4424 - val_accuracy: 0.7922 - val_loss: 0.4732
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4423 - val_accuracy: 0.7987 - val_loss: 0.4727
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4416 - val_accuracy: 0.7987 - val_loss: 0.4721
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4409 - val_accuracy: 0.7987 - val_loss: 0.4717
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4409 - val_accuracy: 0.7987 - val_loss: 0.4723
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4407 - val_accuracy: 0.7922 - val_loss: 0.4736
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4398 - val_accuracy: 0.7922 - val_loss: 0.4732
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4395 - val_accuracy: 0.7987 - val_loss: 0.4727
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4391 - val_accuracy: 0.7987 - val_loss: 0.4727
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4389 - val_accuracy: 0.8052 - val_loss: 0.4729
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4384 - val_accuracy: 0.8117 - val_loss: 0.4716
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4380 - val_accuracy: 0.8117 - val_loss: 0.4705
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4376 - val_accuracy: 0.8052 - val_loss: 0.4717
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4373 - val_accuracy: 0.8052 - val_loss: 0.4723
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4369 - val_accuracy: 0.8052 - val_loss: 0.4719
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4367 - val_accuracy: 0.8117 - val_loss: 0.4707
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4363 - val_accuracy: 0.8182 - val_loss: 0.4710
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4360 - val_accuracy: 0.8117 - val_loss: 0.4706
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4356 - val_accuracy: 0.8117 - val_loss: 0.4694
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4346 - val_accuracy: 0.8182 - val_loss: 0.4690
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4348 - val_accuracy: 0.8117 - val_loss: 0.4688
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4343 - val_accuracy: 0.8182 - val_loss: 0.4693
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4340 - val_accuracy: 0.8182 - val_loss: 0.4700
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4335 - val_accuracy: 0.8117 - val_loss: 0.4702
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4332 - val_accuracy: 0.8052 - val_loss: 0.4687
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4327 - val_accuracy: 0.7987 - val_loss: 0.4685
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4328 - val_accuracy: 0.8052 - val_loss: 0.4696
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4320 - val_accuracy: 0.8182 - val_loss: 0.4702
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4321 - val_accuracy: 0.8052 - val_loss: 0.4708
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4315 - val_accuracy: 0.8052 - val_loss: 0.4701
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4310 - val_accuracy: 0.8117 - val_loss: 0.4699
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4311 - val_accuracy: 0.8052 - val_loss: 0.4700
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4302 - val_accuracy: 0.8052 - val_loss: 0.4685
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4300 - val_accuracy: 0.8052 - val_loss: 0.4689
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4299 - val_accuracy: 0.7987 - val_loss: 0.4694
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4293 - val_accuracy: 0.8052 - val_loss: 0.4682
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4290 - val_accuracy: 0.7987 - val_loss: 0.4682
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4287 - val_accuracy: 0.8052 - val_loss: 0.4674
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4283 - val_accuracy: 0.8117 - val_loss: 0.4681
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4284 - val_accuracy: 0.8117 - val_loss: 0.4685
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4276 - val_accuracy: 0.8117 - val_loss: 0.4688
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7866 - loss: 0.4273 - val_accuracy: 0.8052 - val_loss: 0.4693
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4268 - val_accuracy: 0.8117 - val_loss: 0.4686
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4267 - val_accuracy: 0.8117 - val_loss: 0.4689
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4263 - val_accuracy: 0.8117 - val_loss: 0.4689
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4260 - val_accuracy: 0.8117 - val_loss: 0.4681
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4258 - val_accuracy: 0.8117 - val_loss: 0.4688
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4255 - val_accuracy: 0.8117 - val_loss: 0.4674
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4250 - val_accuracy: 0.8052 - val_loss: 0.4676
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4250 - val_accuracy: 0.8052 - val_loss: 0.4681
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4246 - val_accuracy: 0.8052 - val_loss: 0.4674
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4241 - val_accuracy: 0.8052 - val_loss: 0.4673
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7948 - loss: 0.4237 - val_accuracy: 0.8052 - val_loss: 0.4678
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7980 - loss: 0.4237 - val_accuracy: 0.8052 - val_loss: 0.4678
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7997 - loss: 0.4231 - val_accuracy: 0.8052 - val_loss: 0.4670
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7964 - loss: 0.4231 - val_accuracy: 0.8052 - val_loss: 0.4659
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7980 - loss: 0.4231 - val_accuracy: 0.8052 - val_loss: 0.4661
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7997 - loss: 0.4221 - val_accuracy: 0.8052 - val_loss: 0.4670
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7997 - loss: 0.4217 - val_accuracy: 0.8052 - val_loss: 0.4676
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7997 - loss: 0.4218 - val_accuracy: 0.8052 - val_loss: 0.4671
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8013 - loss: 0.4219 - val_accuracy: 0.8052 - val_loss: 0.4687
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8029 - loss: 0.4210 - val_accuracy: 0.8052 - val_loss: 0.4669

In [81]:
def build_model(hp):
  model = Sequential()

  units = hp.Int('units', 8, 128, step=8)

  model.add(Dense(units = units, activation='relu', input_dim=8))
  model.add(Dense(1, activation = 'sigmoid'))

  model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['accuracy'])

  return model

In [82]:
tuner = kt.RandomSearch(
    build_model,
    objective='val_accuracy',
    max_trials=5,
    directory='mydir',
    project_name='myproject'
)

Reloading Tuner from mydir/myproject/tuner0.json

In [83]:
tuner.search(x_train, y_train, epochs=5, validation_data=(x_test, y_test), verbose=1)

In [84]:
tuner.get_best_hyperparameters()[0].values

{'units': 128}

In [85]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 6 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [86]:
model.fit(x_train, y_train, epochs=100, initial_epoch = 5, validation_data=(x_test, y_test))

Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.7687 - loss: 0.4827 - val_accuracy: 0.8052 - val_loss: 0.4833
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7720 - loss: 0.4672 - val_accuracy: 0.8052 - val_loss: 0.4778
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7752 - loss: 0.4605 - val_accuracy: 0.7922 - val_loss: 0.4753
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4565 - val_accuracy: 0.7987 - val_loss: 0.4745
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4531 - val_accuracy: 0.7922 - val_loss: 0.4744
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7769 - loss: 0.4507 - val_accuracy: 0.7987 - val_loss: 0.4749
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7736 - loss: 0.4479 - val_accuracy: 0.7857 - val_loss: 0.4760
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4456 - val_accuracy: 0.7922 - val_loss: 0.4764
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4451 - val_accuracy: 0.7922 - val_loss: 0.4743
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4430 - val_accuracy: 0.8052 - val_loss: 0.4760
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7752 - loss: 0.4418 - val_accuracy: 0.7922 - val_loss: 0.4764
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4401 - val_accuracy: 0.7987 - val_loss: 0.4754
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7769 - loss: 0.4395 - val_accuracy: 0.7922 - val_loss: 0.4749
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4383 - val_accuracy: 0.7922 - val_loss: 0.4737
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4370 - val_accuracy: 0.7922 - val_loss: 0.4755
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4355 - val_accuracy: 0.7857 - val_loss: 0.4745
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4345 - val_accuracy: 0.7922 - val_loss: 0.4743
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4337 - val_accuracy: 0.7922 - val_loss: 0.4730
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4327 - val_accuracy: 0.7987 - val_loss: 0.4719
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4320 - val_accuracy: 0.7987 - val_loss: 0.4703
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4312 - val_accuracy: 0.7987 - val_loss: 0.4704
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4297 - val_accuracy: 0.7987 - val_loss: 0.4696
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4291 - val_accuracy: 0.8052 - val_loss: 0.4684
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4282 - val_accuracy: 0.7987 - val_loss: 0.4691
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4275 - val_accuracy: 0.7857 - val_loss: 0.4708
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4261 - val_accuracy: 0.7922 - val_loss: 0.4710
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4265 - val_accuracy: 0.7922 - val_loss: 0.4689
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4248 - val_accuracy: 0.7857 - val_loss: 0.4703
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4245 - val_accuracy: 0.7987 - val_loss: 0.4693
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4235 - val_accuracy: 0.7987 - val_loss: 0.4694
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4233 - val_accuracy: 0.7922 - val_loss: 0.4697
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7997 - loss: 0.4215 - val_accuracy: 0.7922 - val_loss: 0.4722
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4216 - val_accuracy: 0.7987 - val_loss: 0.4722
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8046 - loss: 0.4213 - val_accuracy: 0.7922 - val_loss: 0.4703
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4207 - val_accuracy: 0.8052 - val_loss: 0.4712
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4199 - val_accuracy: 0.7922 - val_loss: 0.4734
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8029 - loss: 0.4181 - val_accuracy: 0.8052 - val_loss: 0.4719
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8078 - loss: 0.4185 - val_accuracy: 0.8052 - val_loss: 0.4713
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4174 - val_accuracy: 0.7987 - val_loss: 0.4681
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7980 - loss: 0.4171 - val_accuracy: 0.8052 - val_loss: 0.4684
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4180 - val_accuracy: 0.8052 - val_loss: 0.4691
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8046 - loss: 0.4153 - val_accuracy: 0.7987 - val_loss: 0.4720
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4149 - val_accuracy: 0.8117 - val_loss: 0.4705
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4157 - val_accuracy: 0.8052 - val_loss: 0.4712
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8029 - loss: 0.4143 - val_accuracy: 0.8052 - val_loss: 0.4681
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8111 - loss: 0.4142 - val_accuracy: 0.7987 - val_loss: 0.4711
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8029 - loss: 0.4132 - val_accuracy: 0.8117 - val_loss: 0.4691
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8078 - loss: 0.4117 - val_accuracy: 0.8052 - val_loss: 0.4679
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8029 - loss: 0.4126 - val_accuracy: 0.8052 - val_loss: 0.4684
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8062 - loss: 0.4107 - val_accuracy: 0.8052 - val_loss: 0.4690
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8111 - loss: 0.4115 - val_accuracy: 0.7987 - val_loss: 0.4680
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8127 - loss: 0.4108 - val_accuracy: 0.7987 - val_loss: 0.4699
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8111 - loss: 0.4095 - val_accuracy: 0.7987 - val_loss: 0.4701
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8111 - loss: 0.4082 - val_accuracy: 0.7987 - val_loss: 0.4690
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8176 - loss: 0.4087 - val_accuracy: 0.7922 - val_loss: 0.4705
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8127 - loss: 0.4083 - val_accuracy: 0.7922 - val_loss: 0.4703
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8160 - loss: 0.4071 - val_accuracy: 0.7922 - val_loss: 0.4707
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8127 - loss: 0.4069 - val_accuracy: 0.7922 - val_loss: 0.4731
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8078 - loss: 0.4067 - val_accuracy: 0.7987 - val_loss: 0.4711
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8160 - loss: 0.4056 - val_accuracy: 0.8052 - val_loss: 0.4697
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8241 - loss: 0.4049 - val_accuracy: 0.8052 - val_loss: 0.4686
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8208 - loss: 0.4045 - val_accuracy: 0.7987 - val_loss: 0.4707
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8208 - loss: 0.4043 - val_accuracy: 0.7922 - val_loss: 0.4738
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8160 - loss: 0.4036 - val_accuracy: 0.7922 - val_loss: 0.4748
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8176 - loss: 0.4026 - val_accuracy: 0.7987 - val_loss: 0.4730
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8208 - loss: 0.4030 - val_accuracy: 0.8117 - val_loss: 0.4747
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8192 - loss: 0.4014 - val_accuracy: 0.8052 - val_loss: 0.4721
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8225 - loss: 0.4015 - val_accuracy: 0.7987 - val_loss: 0.4740
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8208 - loss: 0.4007 - val_accuracy: 0.7987 - val_loss: 0.4745
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8208 - loss: 0.4010 - val_accuracy: 0.8052 - val_loss: 0.4698
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8208 - loss: 0.4001 - val_accuracy: 0.8052 - val_loss: 0.4714
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8208 - loss: 0.3999 - val_accuracy: 0.7922 - val_loss: 0.4745
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8274 - loss: 0.3989 - val_accuracy: 0.7987 - val_loss: 0.4696
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8208 - loss: 0.3981 - val_accuracy: 0.7987 - val_loss: 0.4712
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.3976 - val_accuracy: 0.7922 - val_loss: 0.4730
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8208 - loss: 0.3982 - val_accuracy: 0.7987 - val_loss: 0.4747
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8176 - loss: 0.3975 - val_accuracy: 0.8052 - val_loss: 0.4696
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8257 - loss: 0.3969 - val_accuracy: 0.8117 - val_loss: 0.4736
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8208 - loss: 0.3972 - val_accuracy: 0.8117 - val_loss: 0.4742
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8225 - loss: 0.3958 - val_accuracy: 0.8117 - val_loss: 0.4742
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8274 - loss: 0.3960 - val_accuracy: 0.8052 - val_loss: 0.4717
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8290 - loss: 0.3950 - val_accuracy: 0.8117 - val_loss: 0.4714
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8241 - loss: 0.3944 - val_accuracy: 0.8052 - val_loss: 0.4731
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8306 - loss: 0.3939 - val_accuracy: 0.8182 - val_loss: 0.4742
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8225 - loss: 0.3935 - val_accuracy: 0.7987 - val_loss: 0.4760
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8257 - loss: 0.3920 - val_accuracy: 0.8052 - val_loss: 0.4723
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8322 - loss: 0.3926 - val_accuracy: 0.8052 - val_loss: 0.4754
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8322 - loss: 0.3923 - val_accuracy: 0.8052 - val_loss: 0.4774
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8306 - loss: 0.3916 - val_accuracy: 0.8052 - val_loss: 0.4741
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.3910 - val_accuracy: 0.8052 - val_loss: 0.4712
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8306 - loss: 0.3895 - val_accuracy: 0.7987 - val_loss: 0.4752
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8290 - loss: 0.3892 - val_accuracy: 0.8052 - val_loss: 0.4734
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8241 - loss: 0.3890 - val_accuracy: 0.8117 - val_loss: 0.4742
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8290 - loss: 0.3887 - val_accuracy: 0.8052 - val_loss: 0.4722
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8290 - loss: 0.3889 - val_accuracy: 0.7987 - val_loss: 0.4765

In [87]:
def build_model(hp):
  model = Sequential()

  model.add(Dense(72, activation='relu', input_dim=8))

  for i in range(hp.Int('num_layers', min_value=1, max_value=10)):

    model.add(Dense(72, activation='relu'))

  model.add(Dense(1, activation='sigmoid'))

  model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['accuracy'])

  return model

In [88]:
tuner = kt.RandomSearch(
    build_model,
    objective='val_accuracy',
    max_trials=3,
    directory='mydir',
    project_name='myproject1'
)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [89]:
tuner.search(x_train, y_train, epochs=5, validation_data=(x_test, y_test), verbose=1)

Trial 3 Complete [00h 00m 03s]
val_accuracy: 0.8051947951316833

Best val_accuracy So Far: 0.8116883039474487
Total elapsed time: 00h 00m 12s

In [90]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 5}

In [92]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 16 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [93]:
model.fit(x_train, y_train, epochs=100, initial_epoch = 5, validation_data=(x_test, y_test))

Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - accuracy: 0.7704 - loss: 0.4655 - val_accuracy: 0.7857 - val_loss: 0.4789
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.4417 - val_accuracy: 0.7857 - val_loss: 0.4864
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4318 - val_accuracy: 0.7792 - val_loss: 0.4811
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4260 - val_accuracy: 0.7922 - val_loss: 0.4815
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.4134 - val_accuracy: 0.7403 - val_loss: 0.5446
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7997 - loss: 0.4128 - val_accuracy: 0.7857 - val_loss: 0.4920
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.4017 - val_accuracy: 0.7987 - val_loss: 0.4902
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.3987 - val_accuracy: 0.8117 - val_loss: 0.4868
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8257 - loss: 0.3855 - val_accuracy: 0.8052 - val_loss: 0.5015
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.3734 - val_accuracy: 0.7987 - val_loss: 0.5171
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8290 - loss: 0.3753 - val_accuracy: 0.8182 - val_loss: 0.5078
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8322 - loss: 0.3549 - val_accuracy: 0.8052 - val_loss: 0.4927
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8469 - loss: 0.3397 - val_accuracy: 0.7662 - val_loss: 0.5463
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8550 - loss: 0.3383 - val_accuracy: 0.8117 - val_loss: 0.5516
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8502 - loss: 0.3178 - val_accuracy: 0.8117 - val_loss: 0.5455
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8648 - loss: 0.3184 - val_accuracy: 0.7792 - val_loss: 0.5475
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8697 - loss: 0.3083 - val_accuracy: 0.7727 - val_loss: 0.5596
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8876 - loss: 0.2812 - val_accuracy: 0.7857 - val_loss: 0.5738
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8681 - loss: 0.3021 - val_accuracy: 0.7987 - val_loss: 0.5695
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8974 - loss: 0.2529 - val_accuracy: 0.7468 - val_loss: 0.7304
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8925 - loss: 0.2681 - val_accuracy: 0.8052 - val_loss: 0.6181
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9088 - loss: 0.2403 - val_accuracy: 0.7792 - val_loss: 0.6169
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8990 - loss: 0.2406 - val_accuracy: 0.7792 - val_loss: 0.6785
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9104 - loss: 0.2305 - val_accuracy: 0.7792 - val_loss: 0.7664
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9251 - loss: 0.2162 - val_accuracy: 0.7922 - val_loss: 0.6807
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9104 - loss: 0.2117 - val_accuracy: 0.7597 - val_loss: 0.8296
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9479 - loss: 0.1863 - val_accuracy: 0.7922 - val_loss: 0.7197
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9430 - loss: 0.1758 - val_accuracy: 0.7727 - val_loss: 0.7356
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9414 - loss: 0.1598 - val_accuracy: 0.7143 - val_loss: 0.8614
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9446 - loss: 0.1633 - val_accuracy: 0.7468 - val_loss: 0.8138
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9381 - loss: 0.1559 - val_accuracy: 0.7532 - val_loss: 0.8514
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9397 - loss: 0.1608 - val_accuracy: 0.7338 - val_loss: 0.9355
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9544 - loss: 0.1327 - val_accuracy: 0.7338 - val_loss: 0.9218
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9463 - loss: 0.1378 - val_accuracy: 0.7532 - val_loss: 0.9006
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9463 - loss: 0.1389 - val_accuracy: 0.7338 - val_loss: 1.1671
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9658 - loss: 0.0999 - val_accuracy: 0.6429 - val_loss: 1.4511
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9528 - loss: 0.1241 - val_accuracy: 0.7338 - val_loss: 1.2524
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9723 - loss: 0.0854 - val_accuracy: 0.7013 - val_loss: 1.1656
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9495 - loss: 0.1165 - val_accuracy: 0.7338 - val_loss: 1.0933
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9723 - loss: 0.0826 - val_accuracy: 0.7143 - val_loss: 1.1732
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9837 - loss: 0.0541 - val_accuracy: 0.7338 - val_loss: 1.3901
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9495 - loss: 0.1488 - val_accuracy: 0.7208 - val_loss: 1.0831
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9756 - loss: 0.0787 - val_accuracy: 0.7013 - val_loss: 1.2214
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9674 - loss: 0.0912 - val_accuracy: 0.7662 - val_loss: 1.1908
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9723 - loss: 0.0876 - val_accuracy: 0.7013 - val_loss: 1.2955
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9805 - loss: 0.0543 - val_accuracy: 0.7143 - val_loss: 1.3838
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9853 - loss: 0.0454 - val_accuracy: 0.7403 - val_loss: 1.4077
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9642 - loss: 0.1068 - val_accuracy: 0.7013 - val_loss: 1.3397
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9853 - loss: 0.0459 - val_accuracy: 0.7468 - val_loss: 1.6011
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9837 - loss: 0.0603 - val_accuracy: 0.7338 - val_loss: 1.3192
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9919 - loss: 0.0239 - val_accuracy: 0.6429 - val_loss: 2.2421
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9723 - loss: 0.0743 - val_accuracy: 0.7143 - val_loss: 1.4062
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9902 - loss: 0.0333 - val_accuracy: 0.7468 - val_loss: 1.8114
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9691 - loss: 0.0927 - val_accuracy: 0.7013 - val_loss: 1.5341
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9821 - loss: 0.0476 - val_accuracy: 0.7338 - val_loss: 1.5491
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9951 - loss: 0.0240 - val_accuracy: 0.6948 - val_loss: 1.7834
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9902 - loss: 0.0335 - val_accuracy: 0.7338 - val_loss: 1.6551
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9756 - loss: 0.0603 - val_accuracy: 0.6883 - val_loss: 1.8690
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9805 - loss: 0.0599 - val_accuracy: 0.7143 - val_loss: 1.6312
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0103 - val_accuracy: 0.7208 - val_loss: 1.7681
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9821 - loss: 0.0585 - val_accuracy: 0.7078 - val_loss: 1.6178
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9837 - loss: 0.0335 - val_accuracy: 0.7403 - val_loss: 1.6569
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9853 - loss: 0.0567 - val_accuracy: 0.7143 - val_loss: 1.7875
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9967 - loss: 0.0237 - val_accuracy: 0.7273 - val_loss: 1.6886
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9951 - loss: 0.0122 - val_accuracy: 0.7013 - val_loss: 1.8419
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9739 - loss: 0.0624 - val_accuracy: 0.7143 - val_loss: 2.0198
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9870 - loss: 0.0510 - val_accuracy: 0.7273 - val_loss: 1.7379
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9805 - loss: 0.0561 - val_accuracy: 0.7468 - val_loss: 1.7120
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9984 - loss: 0.0085 - val_accuracy: 0.6948 - val_loss: 1.9942
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9837 - loss: 0.0501 - val_accuracy: 0.7013 - val_loss: 1.7619
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9886 - loss: 0.0346 - val_accuracy: 0.7468 - val_loss: 1.8014
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9935 - loss: 0.0178 - val_accuracy: 0.7273 - val_loss: 1.8092
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9837 - loss: 0.0415 - val_accuracy: 0.7273 - val_loss: 1.9073
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9951 - loss: 0.0188 - val_accuracy: 0.6753 - val_loss: 1.9922
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9821 - loss: 0.0436 - val_accuracy: 0.7143 - val_loss: 1.8424
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9984 - loss: 0.0064 - val_accuracy: 0.7662 - val_loss: 1.7973
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9886 - loss: 0.0268 - val_accuracy: 0.7078 - val_loss: 1.9650
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9886 - loss: 0.0311 - val_accuracy: 0.7078 - val_loss: 2.0763
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9788 - loss: 0.0699 - val_accuracy: 0.6948 - val_loss: 1.8799
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0045 - val_accuracy: 0.7273 - val_loss: 1.8625
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9984 - loss: 0.0026 - val_accuracy: 0.7273 - val_loss: 1.9639
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9984 - loss: 0.0071 - val_accuracy: 0.7273 - val_loss: 2.3089
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9870 - loss: 0.0490 - val_accuracy: 0.7013 - val_loss: 2.2575
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0041 - val_accuracy: 0.7013 - val_loss: 2.1326
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9984 - loss: 0.0037 - val_accuracy: 0.7273 - val_loss: 2.1270
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9772 - loss: 0.0672 - val_accuracy: 0.7532 - val_loss: 1.9952
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9919 - loss: 0.0309 - val_accuracy: 0.7208 - val_loss: 2.0896
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9967 - loss: 0.0076 - val_accuracy: 0.7273 - val_loss: 2.1074
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9919 - loss: 0.0279 - val_accuracy: 0.7532 - val_loss: 2.1422
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9967 - loss: 0.0080 - val_accuracy: 0.7078 - val_loss: 2.3629
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9837 - loss: 0.0445 - val_accuracy: 0.7273 - val_loss: 2.0151
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9886 - loss: 0.0448 - val_accuracy: 0.7208 - val_loss: 2.0649
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9886 - loss: 0.0291 - val_accuracy: 0.7403 - val_loss: 1.9680
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9967 - loss: 0.0133 - val_accuracy: 0.7208 - val_loss: 2.0375
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9919 - loss: 0.0290 - val_accuracy: 0.7468 - val_loss: 2.0809

In [115]:
def build_model(hp):

  model = Sequential()

  counter = 0

  for i in range(hp.Int('num_layers', min_value=1, max_value=10)):

    if counter == 0:

      model.add(
          Dense(
              hp.Int('units' + str(i), min_value=8, max_value=128, step=8),
              activation = hp.Choice('activation'+str(i), values=['relu', 'tanh', 'sigmoid', 'selu']),
              input_dim=8
          )
      )
      model.add(Dropout(hp.Choice('dropout' + str(i), values=[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7])))

    else:

      model.add(
          Dense(
              hp.Int('units' + str(i), min_value=8, max_value=128, step=8),
              activation = hp.Choice('activation'+str(i), values=['relu', 'tanh', 'sigmoid', 'selu'])
          )
      )
      model.add(Dropout(hp.Choice('dropout' + str(i), values=[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7])))
    counter += 1

  model.add(Dense(1, activation='sigmoid'))

  model.compile(optimizer=hp.Choice('optimizer', values=['adam', 'rmsprop', 'adagrad', 'sgd']), loss='binary_crossentropy', metrics=['accuracy'])

  return model

In [116]:
tuner = kt.RandomSearch(
    build_model,
    objective='val_accuracy',
    max_trials=3,
    directory='mydir',
    project_name='myproject2'
)

Reloading Tuner from mydir/myproject2/tuner0.json

In [117]:
tuner.search(x_train, y_train, epochs=5, validation_data=(x_test, y_test), verbose=1)

In [118]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 3,
 'units0': 112,
 'activation0': 'sigmoid',
 'optimizer': 'adagrad',
 'units1': 96,
 'activation1': 'tanh',
 'units2': 48,
 'activation2': 'relu',
 'units3': 64,
 'activation3': 'selu',
 'units4': 24,
 'activation4': 'selu',
 'units5': 88,
 'activation5': 'tanh',
 'units6': 56,
 'activation6': 'relu',
 'units7': 48,
 'activation7': 'selu'}

In [119]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'adagrad', because it has 2 variables whereas the saved optimizer has 10 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [120]:
model.fit(x_train, y_train, epochs=200, initial_epoch=5, validation_data=(x_test, y_test))

Epoch 6/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.5814 - loss: 0.6757 - val_accuracy: 0.6494 - val_loss: 0.6543
Epoch 7/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6401 - loss: 0.6617 - val_accuracy: 0.6494 - val_loss: 0.6492
Epoch 8/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6401 - loss: 0.6558 - val_accuracy: 0.6494 - val_loss: 0.6465
Epoch 9/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6466 - loss: 0.6541 - val_accuracy: 0.6429 - val_loss: 0.6451
Epoch 10/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6531 - loss: 0.6474 - val_accuracy: 0.6429 - val_loss: 0.6441
Epoch 11/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6547 - loss: 0.6411 - val_accuracy: 0.6429 - val_loss: 0.6431
Epoch 12/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6482 - loss: 0.6488 - val_accuracy: 0.6429 - val_loss: 0.6423
Epoch 13/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6515 - loss: 0.6488 - val_accuracy: 0.6429 - val_loss: 0.6419
Epoch 14/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6531 - loss: 0.6358 - val_accuracy: 0.6429 - val_loss: 0.6413
Epoch 15/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6466 - loss: 0.6453 - val_accuracy: 0.6429 - val_loss: 0.6407
Epoch 16/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6580 - loss: 0.6450 - val_accuracy: 0.6429 - val_loss: 0.6406
Epoch 17/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6498 - loss: 0.6436 - val_accuracy: 0.6429 - val_loss: 0.6392
Epoch 18/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6564 - loss: 0.6426 - val_accuracy: 0.6429 - val_loss: 0.6380
Epoch 19/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6547 - loss: 0.6381 - val_accuracy: 0.6429 - val_loss: 0.6365
Epoch 20/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6547 - loss: 0.6454 - val_accuracy: 0.6429 - val_loss: 0.6357
Epoch 21/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6482 - loss: 0.6375 - val_accuracy: 0.6429 - val_loss: 0.6357
Epoch 22/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6531 - loss: 0.6326 - val_accuracy: 0.6429 - val_loss: 0.6352
Epoch 23/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6564 - loss: 0.6304 - val_accuracy: 0.6429 - val_loss: 0.6339
Epoch 24/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6564 - loss: 0.6313 - val_accuracy: 0.6429 - val_loss: 0.6331
Epoch 25/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6515 - loss: 0.6352 - val_accuracy: 0.6494 - val_loss: 0.6310
Epoch 26/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6547 - loss: 0.6344 - val_accuracy: 0.6494 - val_loss: 0.6286
Epoch 27/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6498 - loss: 0.6339 - val_accuracy: 0.6494 - val_loss: 0.6289
Epoch 28/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6547 - loss: 0.6358 - val_accuracy: 0.6494 - val_loss: 0.6274
Epoch 29/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6580 - loss: 0.6417 - val_accuracy: 0.6494 - val_loss: 0.6261
Epoch 30/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6547 - loss: 0.6240 - val_accuracy: 0.6494 - val_loss: 0.6257
Epoch 31/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6364 - val_accuracy: 0.6494 - val_loss: 0.6253
Epoch 32/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6515 - loss: 0.6297 - val_accuracy: 0.6494 - val_loss: 0.6239
Epoch 33/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6564 - loss: 0.6320 - val_accuracy: 0.6494 - val_loss: 0.6218
Epoch 34/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6580 - loss: 0.6226 - val_accuracy: 0.6494 - val_loss: 0.6209
Epoch 35/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6515 - loss: 0.6283 - val_accuracy: 0.6494 - val_loss: 0.6185
Epoch 36/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6645 - loss: 0.6262 - val_accuracy: 0.6494 - val_loss: 0.6174
Epoch 37/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6580 - loss: 0.6230 - val_accuracy: 0.6494 - val_loss: 0.6166
Epoch 38/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6564 - loss: 0.6247 - val_accuracy: 0.6494 - val_loss: 0.6151
Epoch 39/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6694 - loss: 0.6242 - val_accuracy: 0.6494 - val_loss: 0.6139
Epoch 40/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6580 - loss: 0.6216 - val_accuracy: 0.6494 - val_loss: 0.6126
Epoch 41/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6482 - loss: 0.6238 - val_accuracy: 0.6494 - val_loss: 0.6122
Epoch 42/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6612 - loss: 0.6129 - val_accuracy: 0.6494 - val_loss: 0.6114
Epoch 43/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6629 - loss: 0.6193 - val_accuracy: 0.6494 - val_loss: 0.6094
Epoch 44/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6596 - loss: 0.6233 - val_accuracy: 0.6494 - val_loss: 0.6074
Epoch 45/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6531 - loss: 0.6218 - val_accuracy: 0.6494 - val_loss: 0.6072
Epoch 46/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6564 - loss: 0.6145 - val_accuracy: 0.6494 - val_loss: 0.6064
Epoch 47/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6629 - loss: 0.6067 - val_accuracy: 0.6494 - val_loss: 0.6048
Epoch 48/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6157 - val_accuracy: 0.6494 - val_loss: 0.6032
Epoch 49/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6645 - loss: 0.6206 - val_accuracy: 0.6494 - val_loss: 0.6017
Epoch 50/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6629 - loss: 0.6168 - val_accuracy: 0.6494 - val_loss: 0.6003
Epoch 51/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6564 - loss: 0.6193 - val_accuracy: 0.6494 - val_loss: 0.6000
Epoch 52/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6629 - loss: 0.6167 - val_accuracy: 0.6494 - val_loss: 0.5992
Epoch 53/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6515 - loss: 0.6162 - val_accuracy: 0.6494 - val_loss: 0.5983
Epoch 54/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6580 - loss: 0.6169 - val_accuracy: 0.6494 - val_loss: 0.5973
Epoch 55/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6661 - loss: 0.6014 - val_accuracy: 0.6494 - val_loss: 0.5953
Epoch 56/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6661 - loss: 0.6066 - val_accuracy: 0.6494 - val_loss: 0.5946
Epoch 57/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6564 - loss: 0.6142 - val_accuracy: 0.6494 - val_loss: 0.5940
Epoch 58/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6629 - loss: 0.6115 - val_accuracy: 0.6494 - val_loss: 0.5933
Epoch 59/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6726 - loss: 0.6010 - val_accuracy: 0.6558 - val_loss: 0.5916
Epoch 60/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6759 - loss: 0.6137 - val_accuracy: 0.6558 - val_loss: 0.5909
Epoch 61/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6580 - loss: 0.6141 - val_accuracy: 0.6558 - val_loss: 0.5908
Epoch 62/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6612 - loss: 0.6041 - val_accuracy: 0.6558 - val_loss: 0.5890
Epoch 63/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6710 - loss: 0.5989 - val_accuracy: 0.6558 - val_loss: 0.5875
Epoch 64/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6612 - loss: 0.6094 - val_accuracy: 0.6558 - val_loss: 0.5868
Epoch 65/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6775 - loss: 0.6010 - val_accuracy: 0.6558 - val_loss: 0.5861
Epoch 66/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6808 - loss: 0.5979 - val_accuracy: 0.6558 - val_loss: 0.5850
Epoch 67/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6629 - loss: 0.6156 - val_accuracy: 0.6688 - val_loss: 0.5840
Epoch 68/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6612 - loss: 0.6047 - val_accuracy: 0.6753 - val_loss: 0.5827
Epoch 69/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6775 - loss: 0.6039 - val_accuracy: 0.6753 - val_loss: 0.5817
Epoch 70/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6792 - loss: 0.5905 - val_accuracy: 0.6753 - val_loss: 0.5812
Epoch 71/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6857 - loss: 0.5945 - val_accuracy: 0.6753 - val_loss: 0.5807
Epoch 72/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6694 - loss: 0.5959 - val_accuracy: 0.6753 - val_loss: 0.5798
Epoch 73/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6661 - loss: 0.6068 - val_accuracy: 0.6753 - val_loss: 0.5789
Epoch 74/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6857 - loss: 0.5866 - val_accuracy: 0.6753 - val_loss: 0.5782
Epoch 75/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6726 - loss: 0.5963 - val_accuracy: 0.6753 - val_loss: 0.5772
Epoch 76/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6661 - loss: 0.5889 - val_accuracy: 0.6753 - val_loss: 0.5768
Epoch 77/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6840 - loss: 0.5910 - val_accuracy: 0.6753 - val_loss: 0.5762
Epoch 78/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6808 - loss: 0.5987 - val_accuracy: 0.6753 - val_loss: 0.5755
Epoch 79/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6710 - loss: 0.5913 - val_accuracy: 0.6753 - val_loss: 0.5737
Epoch 80/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6857 - loss: 0.5865 - val_accuracy: 0.6753 - val_loss: 0.5728
Epoch 81/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6840 - loss: 0.5905 - val_accuracy: 0.6753 - val_loss: 0.5711
Epoch 82/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6824 - loss: 0.5982 - val_accuracy: 0.6753 - val_loss: 0.5703
Epoch 83/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6775 - loss: 0.5983 - val_accuracy: 0.6753 - val_loss: 0.5699
Epoch 84/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6775 - loss: 0.5889 - val_accuracy: 0.6753 - val_loss: 0.5692
Epoch 85/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6792 - loss: 0.5913 - val_accuracy: 0.6753 - val_loss: 0.5682
Epoch 86/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6694 - loss: 0.5887 - val_accuracy: 0.6818 - val_loss: 0.5668
Epoch 87/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6726 - loss: 0.5887 - val_accuracy: 0.6883 - val_loss: 0.5655
Epoch 88/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6661 - loss: 0.5923 - val_accuracy: 0.6883 - val_loss: 0.5646
Epoch 89/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6726 - loss: 0.5940 - val_accuracy: 0.6948 - val_loss: 0.5637
Epoch 90/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6840 - loss: 0.5855 - val_accuracy: 0.6948 - val_loss: 0.5627
Epoch 91/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6906 - loss: 0.5785 - val_accuracy: 0.6883 - val_loss: 0.5625
Epoch 92/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6938 - loss: 0.5801 - val_accuracy: 0.6948 - val_loss: 0.5612
Epoch 93/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6889 - loss: 0.5745 - val_accuracy: 0.6948 - val_loss: 0.5602
Epoch 94/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6987 - loss: 0.5818 - val_accuracy: 0.6883 - val_loss: 0.5591
Epoch 95/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6726 - loss: 0.5825 - val_accuracy: 0.6883 - val_loss: 0.5581
Epoch 96/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6987 - loss: 0.5827 - val_accuracy: 0.6883 - val_loss: 0.5579
Epoch 97/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6792 - loss: 0.5931 - val_accuracy: 0.6883 - val_loss: 0.5568
Epoch 98/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6922 - loss: 0.5855 - val_accuracy: 0.6883 - val_loss: 0.5564
Epoch 99/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6775 - loss: 0.5916 - val_accuracy: 0.6883 - val_loss: 0.5559
Epoch 100/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6938 - loss: 0.5763 - val_accuracy: 0.6883 - val_loss: 0.5548
Epoch 101/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6987 - loss: 0.5723 - val_accuracy: 0.6883 - val_loss: 0.5538
Epoch 102/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7134 - loss: 0.5778 - val_accuracy: 0.6883 - val_loss: 0.5530
Epoch 103/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6938 - loss: 0.5773 - val_accuracy: 0.6883 - val_loss: 0.5528
Epoch 104/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6873 - loss: 0.5833 - val_accuracy: 0.7078 - val_loss: 0.5514
Epoch 105/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6938 - loss: 0.5757 - val_accuracy: 0.7078 - val_loss: 0.5504
Epoch 106/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6987 - loss: 0.5744 - val_accuracy: 0.7143 - val_loss: 0.5493
Epoch 107/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7117 - loss: 0.5723 - val_accuracy: 0.7208 - val_loss: 0.5485
Epoch 108/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7036 - loss: 0.5662 - val_accuracy: 0.7078 - val_loss: 0.5483
Epoch 109/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7003 - loss: 0.5831 - val_accuracy: 0.7208 - val_loss: 0.5472
Epoch 110/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7068 - loss: 0.5781 - val_accuracy: 0.7078 - val_loss: 0.5474
Epoch 111/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7068 - loss: 0.5701 - val_accuracy: 0.7078 - val_loss: 0.5470
Epoch 112/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6922 - loss: 0.5668 - val_accuracy: 0.7143 - val_loss: 0.5457
Epoch 113/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7020 - loss: 0.5683 - val_accuracy: 0.7208 - val_loss: 0.5449
Epoch 114/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7166 - loss: 0.5587 - val_accuracy: 0.7208 - val_loss: 0.5443
Epoch 115/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7101 - loss: 0.5636 - val_accuracy: 0.7208 - val_loss: 0.5431
Epoch 116/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6792 - loss: 0.5812 - val_accuracy: 0.7273 - val_loss: 0.5425
Epoch 117/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7199 - loss: 0.5671 - val_accuracy: 0.7208 - val_loss: 0.5424
Epoch 118/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7003 - loss: 0.5758 - val_accuracy: 0.7273 - val_loss: 0.5414
Epoch 119/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6922 - loss: 0.5728 - val_accuracy: 0.7273 - val_loss: 0.5401
Epoch 120/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7003 - loss: 0.5707 - val_accuracy: 0.7273 - val_loss: 0.5393
Epoch 121/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7052 - loss: 0.5724 - val_accuracy: 0.7273 - val_loss: 0.5391
Epoch 122/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7150 - loss: 0.5702 - val_accuracy: 0.7338 - val_loss: 0.5380
Epoch 123/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7248 - loss: 0.5591 - val_accuracy: 0.7273 - val_loss: 0.5380
Epoch 124/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7036 - loss: 0.5632 - val_accuracy: 0.7273 - val_loss: 0.5376
Epoch 125/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6840 - loss: 0.5604 - val_accuracy: 0.7338 - val_loss: 0.5363
Epoch 126/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7296 - loss: 0.5555 - val_accuracy: 0.7338 - val_loss: 0.5356
Epoch 127/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7052 - loss: 0.5522 - val_accuracy: 0.7273 - val_loss: 0.5344
Epoch 128/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7036 - loss: 0.5690 - val_accuracy: 0.7273 - val_loss: 0.5337
Epoch 129/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7068 - loss: 0.5600 - val_accuracy: 0.7338 - val_loss: 0.5338
Epoch 130/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7182 - loss: 0.5552 - val_accuracy: 0.7273 - val_loss: 0.5327
Epoch 131/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7199 - loss: 0.5584 - val_accuracy: 0.7338 - val_loss: 0.5329
Epoch 132/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7117 - loss: 0.5577 - val_accuracy: 0.7338 - val_loss: 0.5326
Epoch 133/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7101 - loss: 0.5590 - val_accuracy: 0.7338 - val_loss: 0.5316
Epoch 134/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7264 - loss: 0.5501 - val_accuracy: 0.7273 - val_loss: 0.5307
Epoch 135/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7280 - loss: 0.5540 - val_accuracy: 0.7273 - val_loss: 0.5299
Epoch 136/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7134 - loss: 0.5602 - val_accuracy: 0.7273 - val_loss: 0.5300
Epoch 137/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7182 - loss: 0.5609 - val_accuracy: 0.7338 - val_loss: 0.5301
Epoch 138/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7101 - loss: 0.5570 - val_accuracy: 0.7208 - val_loss: 0.5286
Epoch 139/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7280 - loss: 0.5567 - val_accuracy: 0.7273 - val_loss: 0.5278
Epoch 140/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6922 - loss: 0.5585 - val_accuracy: 0.7273 - val_loss: 0.5274
Epoch 141/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7329 - loss: 0.5513 - val_accuracy: 0.7273 - val_loss: 0.5269
Epoch 142/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7117 - loss: 0.5538 - val_accuracy: 0.7273 - val_loss: 0.5258
Epoch 143/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7117 - loss: 0.5584 - val_accuracy: 0.7338 - val_loss: 0.5250
Epoch 144/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7296 - loss: 0.5514 - val_accuracy: 0.7273 - val_loss: 0.5248
Epoch 145/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7166 - loss: 0.5517 - val_accuracy: 0.7273 - val_loss: 0.5243
Epoch 146/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7362 - loss: 0.5420 - val_accuracy: 0.7273 - val_loss: 0.5235
Epoch 147/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7231 - loss: 0.5537 - val_accuracy: 0.7532 - val_loss: 0.5225
Epoch 148/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7117 - loss: 0.5436 - val_accuracy: 0.7597 - val_loss: 0.5219
Epoch 149/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7248 - loss: 0.5588 - val_accuracy: 0.7532 - val_loss: 0.5216
Epoch 150/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7296 - loss: 0.5478 - val_accuracy: 0.7273 - val_loss: 0.5219
Epoch 151/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7280 - loss: 0.5440 - val_accuracy: 0.7273 - val_loss: 0.5214
Epoch 152/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7231 - loss: 0.5493 - val_accuracy: 0.7597 - val_loss: 0.5202
Epoch 153/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7313 - loss: 0.5416 - val_accuracy: 0.7403 - val_loss: 0.5203
Epoch 154/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7248 - loss: 0.5440 - val_accuracy: 0.7468 - val_loss: 0.5196
Epoch 155/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7231 - loss: 0.5437 - val_accuracy: 0.7403 - val_loss: 0.5193
Epoch 156/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7117 - loss: 0.5663 - val_accuracy: 0.7597 - val_loss: 0.5185
Epoch 157/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7329 - loss: 0.5515 - val_accuracy: 0.7597 - val_loss: 0.5179
Epoch 158/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7231 - loss: 0.5473 - val_accuracy: 0.7468 - val_loss: 0.5182
Epoch 159/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7329 - loss: 0.5442 - val_accuracy: 0.7403 - val_loss: 0.5179
Epoch 160/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7329 - loss: 0.5362 - val_accuracy: 0.7468 - val_loss: 0.5173
Epoch 161/200